language: haxe

os:
  - linux
  - osx

osx_image: xcode6.4

haxe:
  - "3.2.1"
  - "3.4.2"
  - development

addons:
  apt:
    packages:
      # Python
      - python3
      # PHP
      - php5-cli
      # C#
      - mono-devel
      - mono-mcs
      # Flash
      - libcurl3:i386
      - libglib2.0-0:i386
      - libx11-6:i386
      - libxext6:i386
      - libxt6:i386
      - libxcursor1:i386
      - libnss3:i386
      - libgtk2.0-0:i386
      # C++
      - gcc-multilib
      - g++-multilib

install:
  # os-specific config
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export DISPLAY=:99.0;
      export AUDIODEV=null;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update;
      brew install mono;
      brew install python3;
    fi
  # Download and setup a standalone flash player debugger
  - haxe flash/install.hxml
  # Install haxelibs
  - if [ "${TRAVIS_HAXE_VERSION}" = "development" ]; then
      haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git;
      pushd $(haxelib path hxcpp | head -1);
        pushd tools/hxcpp; haxe compile.hxml; popd;
        pushd project; neko build.n; popd;
      popd;
    else
      haxelib install hxcpp;
    fi
  - haxelib install hxjava
  - haxelib install hxcs
  - haxelib list

script:
  - pushd tests/all
  -   haxe all.hxml
  - popd
  - pushd tests/bmp
  -   haxe project.hxml
  -   neko bin/tests.n
  -   bin/cpp/Tests
  -   php bin/php/index.php
  -   node bin/tests.js
  -   pushd ../..; haxe flash/run.hxml tests/bmp/bin/tests.swf; popd;
  -   java -jar bin/java/Tests.jar
  -   mono bin/cs/bin/Tests.exe
  - popd
  - pushd tests/elf
  -   haxe elf.hxml
  -   neko bin/elf.n
  - popd
  - pushd tests/gif
  -   haxe project.hxml
  - popd
  - pushd tests/mp3
  -   haxe build.hxml
  - popd
  - pushd tests/pdf
  -   haxe project.hxml
  - popd
  - pushd tests/png
  -   haxe project.hxml
  - popd
  - pushd tests/swf
  -   haxe project.hxml
  -   neko bin/test bin/fibasm.swf
  - popd
  - haxe dox.hxml
  - bash doc-deploy.sh
